
Name=(input("Enter Your Name : "))
Father_Name=(input("Enter Your Father's Name : "))
Mother_Name=(input("Enter Your Mother's Name : "))
DOB=input("Enter Your Date Of Birth : ")
Age=int(input("Enter Your Age : "))
Phone = input("Enter Your Phone Number: ")
Address = input("Enter Your Address: ")
Blood_group = input("Enter Your Blood Group: ")
Hobbies = input("Enter Your Hobbies: ")
Department=(input("Enter Your Department : "))
CGPA=float(input("Enter Your CGPA : "))
Skills=(input("Enter Your Skills : "))
Favourite_course=input("Enter Your Favourite Courses : ")
Favourite_food=input("Enter Your Favourite Foods : ")
Favourite_country=input("Enter Your Favourite Countries : ")
passion=input("Enter Your passion : ")

print("***===============***👩‍🎓👨‍🎓***===============***")
print("-----------------🎓Student Info System🎓-----------------")
print("======================📕📗📘======================")
print("🧑 Name 👧  : ", Name)
print("Father's Name🧑‍🦰      : ", Father_Name)
print("Mother's Name👩‍🦰      : ", Mother_Name)
print("🎈Date of Birth🎉    :", DOB)
print("Age     :", Age)
print("Phone NO    :",Phone)
print("🏘️🏡Address 🏣    :", Address)
print("Blood Group     :", Blood_group)
print("🖋️🍛Hobbies 🎾🏸🏑🎵🎸   :", Hobbies)
print("\n************👩‍🎓👨‍🎓*************\n")
print("Department 👩‍💻  :", Department)
print("CGPA    :", CGPA)
print("Skills 🧑‍💻👩‍🦯💃🚴    :", Skills)
print("📘Favourite Courses📗     :", Favourite_course)
print(" 🥐🍢🍣Favourite Foods🍰🍷🍑   :", Favourite_food)
print(" 🌍Favourite Countries🌏  :", Favourite_country)
print("🧑‍💻Passion🖊️  :", passion)
print("-------------🌺🏵️ Best Wishes 🌸💐-------------")
print("=================================================")
